### ISSUE TITLE
Separate different info into different databases

### ISSUE THREAD

**Issue by nekogravitycat** [nekogravitycat/SchoolNotify#14]
The current database contains keys with `ask`, `info`, and `user` tags. Since we've migrated the database from Redis Enterprise to a local solution, splitting database is good for data management. In conclusion, I'm replacing `data.json` with `sub_ask.json`, `school.json`, and `user.json`.

**Comment by cytsai1008** [comment]
Why not just using a local redid container.

**Comment by nekogravitycat** [comment]
For better data management, as I mentioned earlier in my issue.
Besides, the scale of my database isn't that large and worths creating another container for it.
